### ISSUE TITLE
infer.c:2492:22: error: variable 'last' set but not used [-Werror=unused-but-set-variable]

### ISSUE THREAD

**Issue by Earnestly** [oridb/mc#187]
Small new issue building [latest commit](https://github.com/oridb/mc/commit/178ce0afad1d2ec8af4814ce5970d2e8194b849f) possibly introduced in https://github.com/oridb/mc/commit/cc5182284db2880dcfc3b0bd61dbc6ed319bacc3

```
infer.c: In function 'postinfer':
infer.c:2492:22: error: variable 'last' set but not used [-Werror=unused-but-set-variable]
  Postcheck **post, **last;
                      ^~~~
```

It is just a warning but `-Werror` is set.

**Comment by oridb** [comment]
Thanks, that's what -Werror is for :)

Fixed.
